# conda env create -f environment.yml
name: rooki
channels:
  - conda-forge
dependencies:
  - pip
  #- openssl
  - birdy>=0.8.2
  - beautifulsoup4
  - pymetalink
  - owslib
  - pyproj>=3.0.1
  # open xarray results
  - netcdf4
  - xarray>=0.16
  - cf_xarray
  # tests
  #- pytest
  #- flake8
  ## used for notebooks on binder
  # cdo
  - python-cdo
  - cdo
  # esgf search
  - esgf-pyclient
  # intake catalog
  - intake>=0.7.0,<2.0.0
  - pandas
  - dask
  - fsspec
  - requests
  - aiohttp
  # vis
  - hvplot
  - bokeh
