# conda env create -f environment.yml
name: rooki
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  #- openssl
  - birdy
  # open xarray results
  - netcdf4
  - xarray>=0.15
  # tests
  #- pytest
  #- flake8
  - pip:
    - -e git+https://github.com/metalink-dev/pymetalink.git@master#egg=metalink
