# conda env create -f environment.yml
name: rooki
channels:
  - conda-forge
dependencies:
  - pip
  #- openssl
  - birdy
  - beautifulsoup4
  - pymetalink
  - owslib
  - pyproj>=3.0.1
  # open xarray results
  - netcdf4
  - xarray>=0.16
  # cdo
  - python-cdo
  - cdo
  # esgf search
  - esgf-pyclient
  # intake catalog
  - intake
  - pandas
  - dask
  - fsspec
  - requests
  - aiohttp
  # vis
  - hvplot
  - bokeh
  # tests
  #- pytest
  #- flake8
  - pip:
    - geoip2nation
